os: linux
language: c
compiler: gcc
sudo: required

cache:
        apt: true

notifications:
        email: false

matrix:
        fast_finish: true
        exclude:
                - compiler: gcc
        include:
                - os: linux
                  env:
                          - B=MinGW
                  install:
                          - sudo apt-get install -y gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64
                          - sudo apt-get install -y mingw-w64 mingw-w64-dev
                  script:
                          - make -f Makefile.windows C=1 Q=1
                - os: linux
                  env:
                          - B=Linux
                  install:
                          - sudo apt-get install -y linux-headers-$(uname -r)
                  script:
                          - make
