os: linux
language: c
compiler: gcc
cache:
        apt: true
matrix:
        fast_finish: true
        exclude:
                - compiler: gcc

install:
        - sudo apt-get install -y gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64
        - sudo apt-get install -y mingw-w64 mingw-w64-dev

script:
        - make clean
        - ./build.sh

