os: linux
language: c
compiler: gcc
dist: trusty
sudo: required

cache:
  apt: true

notifications:
  email: false

env:
  global:
    - secure: "bO7lVBHOi821tVLdtk0M38C5eVPeoEdt3EGTZSU8O4R34geUmjYlrBTZycP+6W3LhzeuZ319vcEfGmNYbp/ZOIqZd5ix01a+ALixgrxtfS2ar37HDTPxnr60Y3cBJzfTmIZD0zVSo443V8Yiyqh7hBGjLdy8/JvKLXxQtyhGC6B/hmmVomu9JCNOCYPgXVQzLQMOhKWj4KovvPn6UoEAKBEyKtryxl+mDLKKmfg8CWn+mi/75CbcGtpXpsCVMMIF8Z2At7Yo0dn6UZLX2nVHYVpyY/lp8WR3BgJxNAVApHQkfOJAm0ElSDyo7kFAnv4HAhlpLba2iH4HMvf2o/b+QPKKljahJuzg4pRtUVrV8e7qzTFOYwcmrS2ZUQC5M7xaNyPreBVhz+dOsvdVrt0fGsZjEgPNUcnWRY2UQSel/rulECAECgysaJ/zWs6KrntSMv6GTXuDK7Svv+RlfnqKishKYRdaKpC83DO09hW0+AO6tXDNgqhPQYb6mopXGWG0Hzgo8c6Pq4Qki7ez2QPQoVnq0Fff6cgqVnRbIo8xHb4M8WBFtRTZunL/K8EuPZ0FBIiQIvMujBz1ic4dnUtfLhmXouR+73/NzPE+qgGafW9BOJ9W/qnHfF7SIkSATMquP9wIAdZOXsYGpiyv59h2GZLaW0zQUmZlRaahnCI2UlU="

matrix:
  fast_finish: true
  exclude:
    - compiler: gcc
  include:
  - os: linux
    env:
      - B=MinGW
    install:
      - sudo apt-get install -y gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64
    script:
      - make -f Makefile.windows C=1 Q=1
  - os: linux
    env:
      - B=Linux
    before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
    install:
      - sudo apt-get install -y linux-headers-$(uname -r)
    script:
      - make
    addons:
      coverity_scan:
        project:
          name: "asamy/ksm"
          description: "Build submitted via Travis CI"
        notification_email: f.fallen45@gmail.com
        build_command_prepend: "make clean"
        build_command: "make"
        branch_pattern: master
