os: Visual Studio 2015

branches:
        only:
                - master

platform:
        - x64

configuration:
        - Debug
        - Release

matrix:
        fast_finish: true

artifacts:
        - path: ksm\x64\**\ksm.sys
        - path: ksm\x64\**\ksm_um.exe

